name: 'BHTikTokPlusPlus app'

on:
  workflow_dispatch:
    inputs:

      ipa_url:
        description: "URL to the decrypted IPA file"
        default: ""
        required: true
        type: string

      tweak_url:
        description: "URL to the BHTikTokPlusPlus tweak file"
        default: ""
        required: true
        type: string

      tweak_version:
        description: "The version of the tweak to use."
        default: "1.9.3"
        required: true
        type: string

      display_name:
        description: "App Name (Optional)"
        default: "TikTok"
        required: true
        type: string

      bundle_id:
        description: "BundleID (Optional)"
        default: "com.zhiliaoapp.musically"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.1.1
        with:
          path: main
          submodules: recursive

      - name: Hide sensitive inputs
        uses: levibostian/action-hide-sensitive-inputs@v1

      - name: Validate IPA URL
        run: |
          curl -L -r 0-1023 -o sample.part "${{ inputs.ipa_url }}" > /dev/null 2>&1
          file_type=$(file --mime-type -b sample.part)

          if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
            echo "::error::Validation failed: The file is not a valid IPA file. Detected type: $file_type."
            exit 1
          fi

      - name: Validate Tweak URL
        run: |
          curl -L -r 0-1023 -o sample.part "${{ inputs.tweak_url }}" > /dev/null 2>&1
          file_type=$(file --mime-type -b sample.part)

          if [[ "$file_type" != "application/vnd.debian.binary-package" ]]; then
            echo "::error::Validation failed: The file is not a valid DEB file. Detected type: $file_type."
            exit 1
          fi

      - name: Install Dependencies
        run: brew install make ldid

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

      - name: Cache Theos
        id: theos
        uses: actions/cache@v4
        env:
          cache-name: theos_cache_67db2ab
        with:
          path: theos/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Setup Theos
        if: steps.theos.outputs.cache-hit != 'true'
        uses: actions/checkout@v4.1.7
        with:
          repository: theos/theos
          ref: 67db2ab8d950910161730de77c322658ea3e6b44
          path: ${{ github.workspace }}/theos
          submodules: recursive

      - name: Download iOS SDK
        if: steps.theos.outputs.cache-hit != 'true'
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/theos/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS16.5.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Install cyan
        run: pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip

      - name: Download TikTok
        id: download_tiktok
        run: wget "${{ inputs.ipa_url }}" --no-verbose -O ${{ github.workspace }}/tiktok.ipa

      - name: Download BHTikTokPlusPlus
        id: download_bhttpp
        run: wget "${{ inputs.tweak_url }}" --no-verbose -O ${{ github.workspace }}/bhttpp.deb

      - name: Inject tweaks into IPA
        run: |
          tweaks="bhttpp.deb"

          cyan -i tiktok.ipa -o BHTikTokPlusPlus.ipa -uwef $tweaks -n "${{ inputs.display_name }}" -b ${{ inputs.bundle_id }}

      - name: Prepare TikTok iPA
        id: prepare_tiktok
        run: |
          cd ${{ github.workspace }}
          mv BHTikTokPlusPlus.ipa BHTikTokPlusPlus.zip
          unzip -q HTikTokPlusPlus.zip
          tikTok_version=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "Payload/TikTok.app/Info.plist")
          echo "==> TikTok v$tikTok_version Unziped!"
          echo "tikTok_version=${tikTok_version}" >> $GITHUB_OUTPUT
          cd TikTok.app
          rm -rf Watch
          echo "==> Removed Watch folder"
          rm -rf Extension/*
          echo "==> Removed stock Extensions"
          cd ../..
          zip -r TikTok_$tikTok_version.ipa Payload > /dev/null
          echo "==> TikTok_$tikTok_version.ipa Ziped!"
          rm -rf Payload    

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT: ${{ inputs.create_release }}
        with:
          tag_name: v${{ steps.prepare_tiktok.outputs.tikTok_version }}-${{ inputs.tweak_version  }}
          name: v${{ steps.prepare_tiktok.outputs.tikTok_version }}-${{ inputs.tweak_version  }}
          files: |
            packages/*.deb
            packages/TikTok_${{steps.prepare_tiktok.outputs.tikTok_version}}.ipa
          draft: ${{ env.DRAFT }}
